/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

   
 import { v4 as uuid } from "uuid";
export const videos = [
  {
    _id: uuid(),
    title: "Pirates Of The Carribean",
    thumbnail: "https://i.ytimg.com/vi/maWoEwgEQsY/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDGFc1NMKVctBJQVvnrQQrWeYC-ZA",
    categoryName: "Movies",
    src:'https://youtu.be/maWoEwgEQsY',
    views: "31k",
    date: "Mar 2021",
    creator: "Disney",
  },
  {
    _id: uuid(),
    title: "Beauty and the Beast 'Belle' | Sing-A-Long | Disney",
    thumbnail: "https://i.ytimg.com/vi/tTUZswZHsWQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA1yNycLAWRhV17SetjxLuYHGOPlw",
    categoryName: "Kids",
    src:'https://youtu.be/tTUZswZHsWQ',
    views: "74M",
    date: "Mar 2017",
    creator: "Disney",
  },
  {
    _id: uuid(),
    title: "Pepsi IPL 2015: RCB win thriller against SRH",
    thumbnail: "https://i.ytimg.com/vi/lIFodRLSdy0/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD_B51du85kwOhhf5LmRpMZQ2crCA",
    categoryName: "Sports",
    src:'https://youtu.be/lIFodRLSdy0',
    views: "7M",
    date: "Apr 2021",
    creator: "Hotstar",
  },
  {
    _id: uuid(),
    title: "The incredible MS Dhoni | Player Feature | ICC Cricket World Cup",
    thumbnail: "https://i.ytimg.com/vi/dIpaY_1aoUw/hqdefault.jpg?s…AFwAcABBg==&rs=AOn4CLBR6zBqX6zgU2A3mMF4KoNAuOLtBg",
    categoryName: "Sports",
    src:'https://youtu.be/dIpaY_1aoUw',
    views: "9M",
    date: "June 2021",
    creator: "ICC",
  },
  {
    _id: uuid(),
    title: "SPIDER-MAN HOMECOMING Best Action Scenes",
    thumbnail: "https://i.ytimg.com/vi/TyskcLbCkqE/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLCp4ADQs-1vQg-1NcRYMl2eiSKrbg",
    categoryName: "Movies",
    src:'https://youtu.be/dIpaY_1aoUw',
    views: "11M",
    date: "June 2020",
    creator: "One Media",
  },
  {
    _id: uuid(),
    title: "Titanic 3D Re-Release Official Trailer",
    thumbnail: "https://i.ytimg.com/vi/TyskcLbCkqE/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLCp4ADQs-1vQg-1NcRYMl2eiSKrbg",
    categoryName: "Movies",
    src:'https://youtu.be/dIpaY_1aoUw',
    views: "11M",
    date: "Dec 2011",
    creator: "One Media",
  },
  {
    _id: uuid(),
    title: "MySQL Tutorial for Beginners [Full Course]",
    thumbnail: "https://i.ytimg.com/vi/7S_tz1z_5bA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDQRzwgDiYUwdEuDvClYax7UBqlWA",
    categoryName: "Knowledge",
    src:'https://youtu.be/7S_tz1z_5bA',
    views: "6M",
    date: "May 2022",
    creator: "MOSH",
  },
  {
    _id: uuid(),
    title: "Kota Factory - EP 01 - Inventory",
    thumbnail: "	https://i.ytimg.com/vi/JWbnEt3xuos/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLBuqrw5BQ6o0LLyvRCfQIlZgjEJMg",
    categoryName: "Web Series",
    src:'https://youtu.be/JWbnEt3xuos',
    views: "56M",
    date: "May 2022",
    creator: "TVF",
  },
  {
    _id: uuid(),
    title: "F.R.I.E.N.D.S",
    thumbnail: "	https://i.ytimg.com/vi/a8mgLuqUae4/hqdefault.jpg?s…AFwAcABBg==&rs=AOn4CLBn1JReVPvcv_USpC0XRQIV3V50VA",
    categoryName: "Web Series",
    src:'https://youtu.be/a8mgLuqUae4',
    views: "1M",
    date: "Feb 2020",
    creator: "AF henry",
  },
  {
    _id: uuid(),
    title: "The EARL of BEAN | Mr Bean Cartoon Season 2 ",
    thumbnail: "https://i.ytimg.com/vi/ywBmA3OXdEw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEn0KXSHPfJwLF54Cja47kAqb4Cw",
    categoryName: "Kids",
    src:'https://youtu.be/ywBmA3OXdEw',
    views: "340k",
    date: "May 2022",
    creator: "Mr Bean",
  },
  {
    _id: uuid(),
    title: "Please Find Attached | Mini Web Series",
    thumbnail: "https://i.ytimg.com/vi/IYWK4f1cvy0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBCBoBWUqq9DHLcxf_rODGZJldtSQ",
    categoryName: "Web Series",
    src:'https://youtu.be/IYWK4f1cvy0',
    views: "16M",
    date: "May 2020",
    creator: "Dice Media",
  },
  {
    _id: uuid(),
    title: "map, filter & reduce 🙏 Namaste JavaScript Ep. 19 🔥",
    thumbnail: "https://i.ytimg.com/vi/zdp0zrpKzIE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBwoOnC1M5t9L9FxkDB7w1y6Huq9g",
    categoryName: "Knowledge",
    src:'https://youtu.be/zdp0zrpKzIE',
    views: "304k",
    date: "Nov 2020",
    creator: "Akshay Saini",
  },
];
