import slider1 from "./slider.png"
import slider2 from "./slider4.PNG"
import slider3 from "./slider3.PNG"
import category1 from "./category1.jpg"
import category2 from "./category2.jpg"
import category3 from "./category3.PNG"
import category4 from "./category4.PNG"
import category5 from "./category5.jpg"
import category6 from "./category6.png"
export {slider1,slider2,slider3,category1,category2,category3,category4,category5,category6}